FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["python", "code/Football_player_market_values_predictions/ANN_model_construction_and_training.py"]

